apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-metrics
spec:
  selector:
    matchLabels:
      app: demo-metric
  endpoints:
  - port: http
    path: /actuator/prometheus