apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
data:
  alert.rules: |-
    groups:
    - name: my-app-alerts
      rules:
      - alert: HighErrorRate
        expr: sum(rate(http_server_requests_seconds_count{status="500"}[1m])) / sum(rate(http_server_requests_seconds_count[1m])) > 0.5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
