apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-metrics
  labels:
    app: demo-metric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-metric
  template:
    metadata:
      labels:
        app: demo-metric
    spec:
      containers:
      - name: demo-metrics
        image: dokeryelmariki/demo-metrics:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-metric-service
  labels:
    app: demo-metric
spec:
  selector:
    app: demo-metric
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: LoadBalancer
  